export type UILabels = {
  // Navigation
  analyser: string
  continuer_vendeur: string
  retour_annonce: string
  nouvelle_analyse: string
  telecharger_pdf: string
  // Étape 1 — Score
  score_annonce: string
  voir_detail: string
  masquer_detail: string
  points_attention: string
  // Étape 1 — Réputation
  reputation_modele: string
  bonne_version: string
  pas_meilleure_version: string
  points_forts: string
  problemes_connus: string
  rappels: string
  aucun_rappel: string
  gravite: string
  frequence: string
  gravite_faible: string
  gravite_modere: string
  gravite_eleve: string
  frequence_rare: string
  frequence_occasionnel: string
  frequence_frequent: string
  // Étape 1 — Dépenses
  depenses: string
  depenses_mecaniques: string
  obligatoire_achat: string
  selon_diagnostic: string
  montants_non_inclus: string
  frais_achat: string
  carte_grise: string
  total_certain: string
  poste: string
  detail_col: string
  fourchette: string
  // Étape 1 — Historique
  historique: string
  proprietaires: string
  releve_km: string
  km_coherents: string
  km_suspect: string
  anomalie_km: string
  anomalie_km_detail: string
  // Étape 1 — CTA
  toujours_interesse: string
  modifier_relancer: string
  // Étape 2
  contact_vendeur: string
  message_vendeur: string
  copier: string
  questions: string
  reponses: string
  joindre_docs: string
  analyser_reponses: string
  // Étape 3
  visite: string
  commencer: string
  ok: string
  nok: string
  passer: string
  voir_exemple: string
  etape_suivante: string
  valider_visite: string
  // Étape 4
  decision: string
  verdict: string
  negociation: string
  prix_cible: string
}

const LABELS: Record<string, UILabels> = {
  fr: {
    analyser: 'Analyser',
    continuer_vendeur: "Continuer → Vendeur",
    retour_annonce: "Retour à l'annonce",
    nouvelle_analyse: 'Nouvelle analyse',
    telecharger_pdf: 'Télécharger le rapport PDF',
    score_annonce: "Score de l'annonce",
    voir_detail: 'Voir le détail des critères',
    masquer_detail: 'Masquer le détail',
    points_attention: "Points d'attention",
    reputation_modele: 'Réputation du modèle',
    bonne_version: 'Bonne version',
    pas_meilleure_version: 'Pas la meilleure version',
    points_forts: 'Points forts',
    problemes_connus: 'Problèmes connus',
    rappels: 'Rappels constructeur',
    aucun_rappel: 'Aucun rappel constructeur connu pour ce modèle.',
    gravite: 'Gravité',
    frequence: 'Fréquence',
    gravite_faible: 'Faible',
    gravite_modere: 'Modéré',
    gravite_eleve: 'Élevé',
    frequence_rare: 'Rare',
    frequence_occasionnel: 'Occasionnel',
    frequence_frequent: 'Fréquent',
    depenses: 'Dépenses à prévoir',
    depenses_mecaniques: 'Dépenses mécaniques',
    obligatoire_achat: "À faire obligatoirement à l'achat",
    selon_diagnostic: 'À prévoir selon résultats diagnostic',
    montants_non_inclus: 'Montants non inclus dans le total — dépend des résultats du diagnostic.',
    frais_achat: "Frais d'achat obligatoires",
    carte_grise: 'Carte grise & assurance',
    total_certain: 'Total certain',
    poste: 'Poste',
    detail_col: 'Détail',
    fourchette: 'Fourchette',
    historique: 'Historique du véhicule',
    proprietaires: 'propriétaire(s)',
    releve_km: 'relevé(s) km',
    km_coherents: 'Km cohérents',
    km_suspect: 'Km suspect',
    anomalie_km: 'Anomalie kilométrique détectée',
    anomalie_km_detail: "le compteur pourrait avoir été manipulé. Exigez une explication avant tout achat.",
    toujours_interesse: 'Êtes-vous toujours intéressé par cette annonce ?',
    modifier_relancer: 'Modifier / Relancer',
    contact_vendeur: 'Contact vendeur',
    message_vendeur: 'Message à envoyer au vendeur',
    copier: 'Copier',
    questions: 'Questions incluses',
    reponses: 'Réponses du vendeur',
    joindre_docs: 'Joindre des documents',
    analyser_reponses: 'Analyser les réponses',
    visite: 'Visite du véhicule',
    commencer: "Commencer l'inspection",
    ok: 'OK',
    nok: 'Problème détecté',
    passer: 'Passer',
    voir_exemple: 'Voir un exemple 📷',
    etape_suivante: 'Étape suivante',
    valider_visite: 'Valider la visite',
    decision: 'Décision finale',
    verdict: 'Verdict',
    negociation: 'Arguments de négociation',
    prix_cible: 'Prix cible à proposer',
  },
  en: {
    analyser: 'Analyse',
    continuer_vendeur: 'Continue → Seller',
    retour_annonce: 'Back to listing',
    nouvelle_analyse: 'New analysis',
    telecharger_pdf: 'Download PDF Report',
    score_annonce: 'Listing Score',
    voir_detail: 'View detailed criteria',
    masquer_detail: 'Hide details',
    points_attention: 'Key Points',
    reputation_modele: 'Model Reputation',
    bonne_version: 'Good version',
    pas_meilleure_version: 'Not the best version',
    points_forts: 'Strengths',
    problemes_connus: 'Known Issues',
    rappels: 'Manufacturer Recalls',
    aucun_rappel: 'No known manufacturer recalls for this model.',
    gravite: 'Severity',
    frequence: 'Frequency',
    gravite_faible: 'Low',
    gravite_modere: 'Moderate',
    gravite_eleve: 'High',
    frequence_rare: 'Rare',
    frequence_occasionnel: 'Occasional',
    frequence_frequent: 'Frequent',
    depenses: 'Estimated Costs',
    depenses_mecaniques: 'Mechanical Costs',
    obligatoire_achat: 'Required at Purchase',
    selon_diagnostic: 'Depending on Inspection Results',
    montants_non_inclus: 'Amounts not included in total — depends on diagnostic results.',
    frais_achat: 'Mandatory Purchase Fees',
    carte_grise: 'Registration & Insurance',
    total_certain: 'Confirmed Total',
    poste: 'Item',
    detail_col: 'Detail',
    fourchette: 'Range',
    historique: 'Vehicle History',
    proprietaires: 'owner(s)',
    releve_km: 'mileage record(s)',
    km_coherents: 'Consistent Mileage',
    km_suspect: 'Suspicious Mileage',
    anomalie_km: 'Mileage anomaly detected',
    anomalie_km_detail: 'the odometer may have been tampered with. Request an explanation before purchasing.',
    toujours_interesse: 'Are you still interested in this listing?',
    modifier_relancer: 'Edit / Restart',
    contact_vendeur: 'Seller Contact',
    message_vendeur: 'Message to send to the seller',
    copier: 'Copy',
    questions: 'Included questions',
    reponses: "Seller's answers",
    joindre_docs: 'Attach documents',
    analyser_reponses: 'Analyse answers',
    visite: 'Vehicle Inspection',
    commencer: 'Start inspection',
    ok: 'OK',
    nok: 'Issue found',
    passer: 'Skip',
    voir_exemple: 'See an example 📷',
    etape_suivante: 'Next step',
    valider_visite: 'Validate visit',
    decision: 'Final Decision',
    verdict: 'Verdict',
    negociation: 'Negotiation Arguments',
    prix_cible: 'Target price to propose',
  },
  es: {
    analyser: 'Analizar',
    continuer_vendeur: 'Continuar → Vendedor',
    retour_annonce: 'Volver al anuncio',
    nouvelle_analyse: 'Nuevo análisis',
    telecharger_pdf: 'Descargar informe PDF',
    score_annonce: 'Puntuación del anuncio',
    voir_detail: 'Ver criterios detallados',
    masquer_detail: 'Ocultar detalles',
    points_attention: 'Puntos de atención',
    reputation_modele: 'Reputación del modelo',
    bonne_version: 'Buena versión',
    pas_meilleure_version: 'No es la mejor versión',
    points_forts: 'Puntos fuertes',
    problemes_connus: 'Problemas conocidos',
    rappels: 'Recalls del fabricante',
    aucun_rappel: 'No se conocen recalls del fabricante para este modelo.',
    gravite: 'Gravedad',
    frequence: 'Frecuencia',
    gravite_faible: 'Baja',
    gravite_modere: 'Moderada',
    gravite_eleve: 'Alta',
    frequence_rare: 'Rara',
    frequence_occasionnel: 'Ocasional',
    frequence_frequent: 'Frecuente',
    depenses: 'Gastos previstos',
    depenses_mecaniques: 'Gastos mecánicos',
    obligatoire_achat: 'Obligatorio al comprar',
    selon_diagnostic: 'Según resultados del diagnóstico',
    montants_non_inclus: 'Importes no incluidos en el total — depende de los resultados del diagnóstico.',
    frais_achat: 'Gastos obligatorios de compra',
    carte_grise: 'Matrícula y seguro',
    total_certain: 'Total confirmado',
    poste: 'Concepto',
    detail_col: 'Detalle',
    fourchette: 'Rango',
    historique: 'Historial del vehículo',
    proprietaires: 'propietario(s)',
    releve_km: 'registro(s) de km',
    km_coherents: 'Km coherentes',
    km_suspect: 'Km sospechosos',
    anomalie_km: 'Anomalía kilométrica detectada',
    anomalie_km_detail: 'el cuentakilómetros puede haber sido manipulado. Exija una explicación antes de comprar.',
    toujours_interesse: '¿Sigue interesado en este anuncio?',
    modifier_relancer: 'Editar / Reiniciar',
    contact_vendeur: 'Contacto vendedor',
    message_vendeur: 'Mensaje a enviar al vendedor',
    copier: 'Copiar',
    questions: 'Preguntas incluidas',
    reponses: 'Respuestas del vendedor',
    joindre_docs: 'Adjuntar documentos',
    analyser_reponses: 'Analizar respuestas',
    visite: 'Visita del vehículo',
    commencer: 'Comenzar inspección',
    ok: 'OK',
    nok: 'Problema detectado',
    passer: 'Saltar',
    voir_exemple: 'Ver un ejemplo 📷',
    etape_suivante: 'Siguiente paso',
    valider_visite: 'Validar visita',
    decision: 'Decisión final',
    verdict: 'Veredicto',
    negociation: 'Argumentos de negociación',
    prix_cible: 'Precio objetivo',
  },
  pt: {
    analyser: 'Analisar',
    continuer_vendeur: 'Continuar → Vendedor',
    retour_annonce: 'Voltar ao anúncio',
    nouvelle_analyse: 'Nova análise',
    telecharger_pdf: 'Descarregar relatório PDF',
    score_annonce: 'Pontuação do anúncio',
    voir_detail: 'Ver critérios detalhados',
    masquer_detail: 'Ocultar detalhes',
    points_attention: 'Pontos de atenção',
    reputation_modele: 'Reputação do modelo',
    bonne_version: 'Boa versão',
    pas_meilleure_version: 'Não é a melhor versão',
    points_forts: 'Pontos fortes',
    problemes_connus: 'Problemas conhecidos',
    rappels: 'Recalls do fabricante',
    aucun_rappel: 'Nenhum recall do fabricante conhecido para este modelo.',
    gravite: 'Gravidade',
    frequence: 'Frequência',
    gravite_faible: 'Baixa',
    gravite_modere: 'Moderada',
    gravite_eleve: 'Alta',
    frequence_rare: 'Rara',
    frequence_occasionnel: 'Ocasional',
    frequence_frequent: 'Frequente',
    depenses: 'Despesas previstas',
    depenses_mecaniques: 'Despesas mecânicas',
    obligatoire_achat: 'Obrigatório na compra',
    selon_diagnostic: 'Conforme resultados do diagnóstico',
    montants_non_inclus: 'Valores não incluídos no total — depende dos resultados do diagnóstico.',
    frais_achat: 'Custos obrigatórios de compra',
    carte_grise: 'Registro e seguro',
    total_certain: 'Total confirmado',
    poste: 'Item',
    detail_col: 'Detalhe',
    fourchette: 'Intervalo',
    historique: 'Histórico do veículo',
    proprietaires: 'proprietário(s)',
    releve_km: 'registro(s) de km',
    km_coherents: 'Km coerentes',
    km_suspect: 'Km suspeitos',
    anomalie_km: 'Anomalia quilométrica detectada',
    anomalie_km_detail: 'o odômetro pode ter sido adulterado. Exija uma explicação antes de comprar.',
    toujours_interesse: 'Ainda tem interesse neste anúncio?',
    modifier_relancer: 'Editar / Reiniciar',
    contact_vendeur: 'Contacto vendedor',
    message_vendeur: 'Mensagem a enviar ao vendedor',
    copier: 'Copiar',
    questions: 'Perguntas incluídas',
    reponses: 'Respostas do vendedor',
    joindre_docs: 'Anexar documentos',
    analyser_reponses: 'Analisar respostas',
    visite: 'Visita do veículo',
    commencer: 'Começar inspeção',
    ok: 'OK',
    nok: 'Problema detetado',
    passer: 'Saltar',
    voir_exemple: 'Ver um exemplo 📷',
    etape_suivante: 'Próximo passo',
    valider_visite: 'Validar visita',
    decision: 'Decisão final',
    verdict: 'Veredicto',
    negociation: 'Argumentos de negociação',
    prix_cible: 'Preço alvo',
  },
  it: {
    analyser: 'Analizza',
    continuer_vendeur: 'Continua → Venditore',
    retour_annonce: "Torna all'annuncio",
    nouvelle_analyse: 'Nuova analisi',
    telecharger_pdf: 'Scarica report PDF',
    score_annonce: 'Punteggio annuncio',
    voir_detail: 'Vedi criteri dettagliati',
    masquer_detail: 'Nascondi dettagli',
    points_attention: 'Punti di attenzione',
    reputation_modele: 'Reputazione del modello',
    bonne_version: 'Buona versione',
    pas_meilleure_version: 'Non la versione migliore',
    points_forts: 'Punti di forza',
    problemes_connus: 'Problemi noti',
    rappels: 'Richiami del costruttore',
    aucun_rappel: 'Nessun richiamo del costruttore noto per questo modello.',
    gravite: 'Gravità',
    frequence: 'Frequenza',
    gravite_faible: 'Bassa',
    gravite_modere: 'Moderata',
    gravite_eleve: 'Alta',
    frequence_rare: 'Rara',
    frequence_occasionnel: 'Occasionale',
    frequence_frequent: 'Frequente',
    depenses: 'Spese previste',
    depenses_mecaniques: 'Spese meccaniche',
    obligatoire_achat: "Obbligatorio all'acquisto",
    selon_diagnostic: 'In base ai risultati della diagnosi',
    montants_non_inclus: 'Importi non inclusi nel totale — dipende dai risultati della diagnosi.',
    frais_achat: 'Spese obbligatorie di acquisto',
    carte_grise: 'Immatricolazione e assicurazione',
    total_certain: 'Totale confermato',
    poste: 'Voce',
    detail_col: 'Dettaglio',
    fourchette: 'Intervallo',
    historique: 'Storico del veicolo',
    proprietaires: 'proprietario/i',
    releve_km: 'rilevazione/i km',
    km_coherents: 'Km coerenti',
    km_suspect: 'Km sospetti',
    anomalie_km: 'Anomalia chilometrica rilevata',
    anomalie_km_detail: "il contachilometri potrebbe essere stato manomesso. Richiedere una spiegazione prima dell'acquisto.",
    toujours_interesse: 'Sei ancora interessato a questo annuncio?',
    modifier_relancer: 'Modifica / Riavvia',
    contact_vendeur: 'Contatto venditore',
    message_vendeur: 'Messaggio da inviare al venditore',
    copier: 'Copia',
    questions: 'Domande incluse',
    reponses: 'Risposte del venditore',
    joindre_docs: 'Allegare documenti',
    analyser_reponses: 'Analizza risposte',
    visite: 'Visita del veicolo',
    commencer: 'Inizia ispezione',
    ok: 'OK',
    nok: 'Problema rilevato',
    passer: 'Salta',
    voir_exemple: 'Vedi un esempio 📷',
    etape_suivante: 'Passo successivo',
    valider_visite: 'Valida visita',
    decision: 'Decisione finale',
    verdict: 'Verdetto',
    negociation: 'Argomenti di trattativa',
    prix_cible: 'Prezzo obiettivo',
  },
  de: {
    analyser: 'Analysieren',
    continuer_vendeur: 'Weiter → Verkäufer',
    retour_annonce: 'Zurück zur Anzeige',
    nouvelle_analyse: 'Neue Analyse',
    telecharger_pdf: 'PDF-Bericht herunterladen',
    score_annonce: 'Anzeigenbewertung',
    voir_detail: 'Detaillierte Kriterien anzeigen',
    masquer_detail: 'Details ausblenden',
    points_attention: 'Aufmerksamkeitspunkte',
    reputation_modele: 'Modellreputation',
    bonne_version: 'Gute Version',
    pas_meilleure_version: 'Nicht die beste Version',
    points_forts: 'Stärken',
    problemes_connus: 'Bekannte Probleme',
    rappels: 'Rückrufe des Herstellers',
    aucun_rappel: 'Keine bekannten Rückrufe des Herstellers für dieses Modell.',
    gravite: 'Schwere',
    frequence: 'Häufigkeit',
    gravite_faible: 'Niedrig',
    gravite_modere: 'Mäßig',
    gravite_eleve: 'Hoch',
    frequence_rare: 'Selten',
    frequence_occasionnel: 'Gelegentlich',
    frequence_frequent: 'Häufig',
    depenses: 'Voraussichtliche Kosten',
    depenses_mecaniques: 'Mechanische Kosten',
    obligatoire_achat: 'Beim Kauf erforderlich',
    selon_diagnostic: 'Je nach Diagnoseergebnis',
    montants_non_inclus: 'Beträge nicht im Gesamtbetrag enthalten — hängt von den Diagnoseergebnissen ab.',
    frais_achat: 'Pflichtgebühren beim Kauf',
    carte_grise: 'Zulassung & Versicherung',
    total_certain: 'Bestätigtes Gesamt',
    poste: 'Posten',
    detail_col: 'Detail',
    fourchette: 'Bereich',
    historique: 'Fahrzeughistorie',
    proprietaires: 'Eigentümer',
    releve_km: 'km-Aufzeichnung(en)',
    km_coherents: 'Konsistenter km-Stand',
    km_suspect: 'Verdächtiger km-Stand',
    anomalie_km: 'Kilometerstands-Anomalie erkannt',
    anomalie_km_detail: 'Der Tacho könnte manipuliert worden sein. Verlangen Sie eine Erklärung vor dem Kauf.',
    toujours_interesse: 'Sind Sie noch an diesem Inserat interessiert?',
    modifier_relancer: 'Bearbeiten / Neu starten',
    contact_vendeur: 'Verkäuferkontakt',
    message_vendeur: 'Nachricht an den Verkäufer',
    copier: 'Kopieren',
    questions: 'Enthaltene Fragen',
    reponses: 'Antworten des Verkäufers',
    joindre_docs: 'Dokumente anhängen',
    analyser_reponses: 'Antworten analysieren',
    visite: 'Fahrzeuginspektion',
    commencer: 'Inspektion starten',
    ok: 'OK',
    nok: 'Problem festgestellt',
    passer: 'Überspringen',
    voir_exemple: 'Beispiel anzeigen 📷',
    etape_suivante: 'Nächster Schritt',
    valider_visite: 'Inspektion bestätigen',
    decision: 'Endentscheidung',
    verdict: 'Urteil',
    negociation: 'Verhandlungsargumente',
    prix_cible: 'Zielpreis',
  },
}

const countryLangMap: Record<string, string> = {
  'France': 'fr', 'Belgique': 'fr', 'Suisse': 'fr',
  'Canada': 'en', 'USA': 'en', 'United States': 'en',
  'UK': 'en', 'United Kingdom': 'en', 'Australia': 'en', 'Ireland': 'en',
  'Spain': 'es', 'Espagne': 'es',
  'Italy': 'it', 'Italie': 'it',
  'Portugal': 'pt', 'Brazil': 'pt', 'Brésil': 'pt',
  'Allemagne': 'de', 'Germany': 'de', 'Austria': 'de', 'Autriche': 'de',
  'Netherlands': 'nl', 'Pays-Bas': 'nl',
}

export function getLabels(country: string): UILabels {
  const lang = countryLangMap[country] ?? 'fr'
  return LABELS[lang] ?? LABELS.fr
}
